### ISSUE TITLE
Usage of library with ProcessPoolExecutor raise concurrent.futures.process.BrokenProcessPool

### ISSUE THREAD

**Issue by ghost** [jtgrassie/pyrx#10]
Hello i'm trying to use the library with ProcessPoolExecutor to get a better hashrate on monero mining but everytime the pyrx.get_rx_hash is executed into the process it raise an exception like this :

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test2.py", line 290, in start
    totalHashrate += future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending..`

**Comment by peter-rs** [comment]
From the error message shown, this does not look to be a pyrx problem. Please either show a more specific error message that points to pyrx as the root cause of this issue.

**Comment by TungKaiYing** [comment]
I've identified the error, the process are killed by oom killer because the
system run out of memory during pyrx initialization ! Here the logs :

[37775.066200] python3 invoked oom-killer:
gfp_mask=0x100dca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0
[37775.066479]
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-29.scope,task=
              python3,pid=15079,uid=0
[37775.066533] Out of memory: Killed process 15079 (python3)
total-vm:2639560kB,anon-rss:624304kB, file-rss:4kB, shmem-rss:8kB, UID:0
pgtables:1336kB oom_score_adj:0

Any suggestion to only initialize pyrx one time for two process or maybe to
reduce memory usage of it ?

**Comment by ghost** [comment]
I've identified the error, the process are killed by oom killer because the
system run out of memory during pyrx initialization ! Here the logs :

```
[37775.066200] python3 invoked oom-killer:
gfp_mask=0x100dca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0
[37775.066479]
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-29.scope,task=python3,pid=15079,uid=0
[37775.066533] Out of memory: Killed process 15079 (python3)
total-vm:2639560kB,anon-rss:624304kB, file-rss:4kB, shmem-rss:8kB, UID:0
pgtables:1336kB oom_score_adj:0
```

Any suggestion to only initialize pyrx one time for two process or maybe to
reduce memory usage of it ?

**Comment by ghost** [comment]
I've solved the issue by measuring the available free memory and divid it by the number of cpu cores then i define the maximum usage of memory per process with this function :

`def initializer(self):
        gc.collect()

        free_memory = 0

        with open('/proc/meminfo', 'r') as mem:
            for i in mem:
                sline = i.split()
                if str(sline[0]) in ('MemFree:', 'Buffers:', 'Cached:'):
                    free_memory += int(sline[1])

        soft, hard = resource.getrlimit(resource.RLIMIT_AS)
        resource.setrlimit(resource.RLIMIT_AS, (int(free_memory * 1024 / 2), hard))`

Unfortunetly it lead to not being able to use large page i don't know why i've tried to add this :

`os.system("sysctl -w vm.nr_hugepages=1280")`

inside the initializer without success maybe it should not be 1280 but another value because of the number of process ?

Edit :

Pyrx is in fact initialized two times because there is two cores on the processor and Processpoolexecutor start two process. How to initialize only one time pyrx ? thanks

**Comment by ghost** [comment]
Nobody have the solution to initialize pyrx one time and use it in two different process ? I mean with the same dataset ? Process can help to gain some power compare to thread thats why im trying this way. Im still stuck there.

**Comment by jtgrassie** [comment]
This is not a support forum, it's a bug tracker, and this is not a bug.
