### ISSUE TITLE
problems while running on low end machines

### ISSUE THREAD

**Issue by VYOM00907** [jtgrassie/pyrx#17]
greetings,
@jtgrassie are there ways to enhance the ram usage for low end machines as it uses the whole ram and sometimes it crashes the machine and not able to mine and  i am using 2 gm ram and 2 core cpu

**Comment by VYOM00907** [comment]
@jtgrassie  can pyrx be used with numba for efficiency of cpu processing as numba compiles pyrx for ready use

**Comment by jtgrassie** [comment]
You can set the environment variable `MONERO_RANDOMX_UMASK=4` to run in light mode.
