### ISSUE TITLE
randomx: Couldn't use largePages for RandomX ...

### ISSUE THREAD

**Issue by gamesguru** [jtgrassie/pyrx#2]
also, it is VERY slow the first time.  How does this compare to C implementation of RandomX?

Are the hashes reproducible like this, or do we have to report certain steps failed and were skipped?
Thanks

```
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
randomx: Couldn't use largePages for RandomX VM
```

**Comment by jtgrassie** [comment]
This project merely wraps the [RandomX library](https://github.com/tevador/RandomX), it is not a Python implementation of RandomX.

> randomx: Couldn't use largePages

Which a message from the RandomX library. You are supposed to enable large page support in your OS. If you don't, the library won't use large pages.

> also, it is VERY slow the first time

Correct. That is the RandomX dataset allocation and initialization.

**Comment by gamesguru** [comment]
Are there any docs on how it's run in coin protocols?

**Comment by jtgrassie** [comment]
> Are there any docs on how it's run in coin protocols?

What does that even mean?

**Comment by gamesguru** [comment]
classic hash is simple, first person to find hash below say 00000FFF000000, wins.  It involves lots of calculations, billions or more.

RandomX is used for more than 1 loop i assume, few thousand or million?

**Comment by jtgrassie** [comment]
RandomX is just like any other hashing function in this regard. It takes input data and outputs a hash.

**Comment by gamesguru** [comment]
interesting.  So it can still make fair comparison if one peer is missing the "large page support" ?

Do you know about the iterations per second?

**Comment by jtgrassie** [comment]
> So it can still make fair comparison if one peer is missing the "large page support" ?

If using for *mining* of course one wants optimal configuration and thus would need to configure their system for large page support.

> Do you know about the iterations per second?

This depends on hardware. For information about RandomX why don't you go to the source?  https://github.com/tevador/RandomX

GitHub Issues are for bug tracking, not general questions and support.
