### ISSUE TITLE
how to make pyrx use light mode of random X miner 

### ISSUE THREAD

**Issue by BACKUP00907** [jtgrassie/pyrx#20]
Greetings I need help on this to make pyrx use light mode of random X miner to be able to work with less memory ; how to enable lightmode in pyrx of randomx

**Comment by BACKUP00907** [comment]
how to enable lightmode in pyrx of randomx

**Comment by jtgrassie** [comment]
<code>env <b>MONERO_RANDOMX_UMASK=4</b> python tests/test.py</code>
