### ISSUE TITLE
Add support for ARM

### ISSUE THREAD

**Issue by pdxwebdev** [jtgrassie/pyrx#9]
After testing on RaspberryPi 8GB and 4GB, I receive a core dump error.

I've tested ARM releases of both Ubuntu and Windows. Same error.

I understand you are extremely busy and your time is very valuable so if you can even point me in the right direct so I can perhaps fix the issue myself and submit a PR I would be vert grateful. Thank you.

**Comment by peter-rs** [comment]
Not able to replicate issue, What RaspberryPi are you using?

Pyrx installs perfectly on Raspberry Pi 4b 8Gb model running Ubuntu 21.04

**Comment by pdxwebdev** [comment]
@pebu1337 My apologies. Yes, it will install. The error occurs when you try to generate a hash using `get_rx_hash`

**Comment by peter-rs** [comment]
![pyrx](https://user-images.githubusercontent.com/34286598/152436003-75a0104e-d538-4d2f-9cb8-f577681bd78c.png)
Unfortunately, not able to replicate your error still.

**Comment by pdxwebdev** [comment]
@pebu1337 Thank you for testing on your end. I will test on my end to further isolate the issue.

**Comment by pdxwebdev** [comment]
@pebu1337 Just updated my branch with the latest updates from Jan 31st and it's working! Thank you for checking!
